### ISSUE TITLE
运行一天后崩溃

### ISSUE THREAD

**Issue by chk-jxcn** [cherrot/gochinadns#14]
运行参数：
`chinadns -c /etc/tinc/conf/china.txt -s 114.114.114.114 -trusted-servers 8.8.8.8`

目前只有堆栈打印
```
time="2019-06-09T00:33:32+08:00" level=error msg="Fail to send UDP query. Will retry in TCP." error="read udp 192.168.192.210:38595->8.8.8.8:53: i/o timeout" question="www.gstatic.com. A" server="8.8.8.8:53"
time="2019-06-09T00:33:33+08:00" level=error msg="Fail to send TCP query." error="dial tcp 8.8.8.8:53: i/o timeout" question="www.gstatic.com. A" server="8.8.8.8:53"
time="2019-06-09T00:33:33+08:00" level=error msg="Error hanppens." error="0: dial tcp 8.8.8.8:53: i/o timeout" question="www.gstatic.com. A"
time="2019-06-09T00:33:34+08:00" level=error msg="Fail to send UDP query. Will retry in TCP." error="read udp 192.168.192.210:38650->8.8.8.8:53: i/o timeout" question="init.itunes.apple.com. A" server="8.8.8.8:53"
time="2019-06-09T00:33:35+08:00" level=error msg="Fail to send UDP query. Will retry in TCP." error="read udp 192.168.192.210:35226->8.8.8.8:53: i/o timeout" question="xp.apple.com. A" server="8.8.8.8:53"
time="2019-06-09T00:33:35+08:00" level=error msg="Fail to send UDP query. Will retry in TCP." error="read udp 192.168.192.210:60947->8.8.8.8:53: i/o timeout" question="itunes.apple.com. A" server="8.8.8.8:53"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61a2c0]

goroutine 131600 [running]:
github.com/miekg/dns.(*Msg).SetEdns0(...)
        C:/Users/Admin/go/pkg/mod/github.com/miekg/dns@v1.1.9/defaults.go:130
github.com/cherrot/gochinadns.setUDPSize(0xc0006c0900, 0x582, 0x69e45a)
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:183 +0xf0
github.com/cherrot/gochinadns.(*Server).Lookup(0xc000383fb0, 0xc0006c0900, 0xc000012344, 0xa, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:81 +0x433
github.com/cherrot/gochinadns.(*Server).Lookup-fm(0xc0006c0900, 0xc000012344, 0xa, 0x645d20, 0xc0004f7e20, 0xc0006fed20, 0x25)
        C:/Users/Admin/Desktop/gochinadns-master/dns.go:43 +0x48
github.com/cherrot/gochinadns.lookupInServers.func1(0x0, 0xc000012344, 0xa)
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:34 +0x14b
created by github.com/cherrot/gochinadns.lookupInServers
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:56 +0x538
"./root/chinadns-1.3.2/nohup.out" 3261L, 586365C                                
```

**Comment by cherrot** [comment]
现在能稳定出现么？

**Comment by chk-jxcn** [comment]
> 现在能稳定出现么？

应该可以，在centos和freebsd上都出现了，而且都是AMD64的版本，现在enable了coredump，等下一次出来再看看

**Comment by cherrot** [comment]
好的，感谢！

**Comment by cherrot** [comment]
这个栈太诡异了。。如果真的出现空指针，那应该在176行就挂掉了才对。。

https://github.com/cherrot/gochinadns/blob/983112171aeab34c1d2f8ae8438e902c06fe1f2f/lookup.go#L176-L183

**Comment by chk-jxcn** [comment]
> 这个栈太诡异了。。如果真的出现空指针，那应该在176行就挂掉了才对。。
> 
> https://github.com/cherrot/gochinadns/blob/983112171aeab34c1d2f8ae8438e902c06fe1f2f/lookup.go#L176-L183

看起来req不是空指针。。但是dns.Extra可能没有初始化，然后就挂了。。

**Comment by chk-jxcn** [comment]
req好像是在多个线程里用？但是dns.Extra = dns.Extra.append应该不是线程安全的。

**Comment by chk-jxcn** [comment]
加了coredump结果好几天没出现了。【捂脸

**Comment by cherrot** [comment]
确实存在竞态条件，最开始实现时没考虑会就地修改dns request的情况。不过应该只有dns request为nil的情况下才会出现空指针异常，这是没想通的地方。

竞态条件可以通过`go build -race`添加竞态检查看一下，多谢！

**Comment by chk-jxcn** [comment]
又崩溃了一次，但是设置了GOTRACEBACK=crash好像也没有coredump出来。
确定其他程序是可以core出来的，而且ulimit -c 是unlimited

```
time="2019-06-11T10:49:12+08:00" level=error msg="Fail to send UDP query. Will retry in TCP." error="read udp 192.168.1.2:45645->114.114.114.114:53: i/o timeout" question="129.36.168.192.in-addr.arpa. PTR" server="114.114.114.114:53"
time="2019-06-11T10:49:12+08:00" level=error msg="Fail to send TCP query." error="read tcp 192.168.1.2:40234->114.114.114.114:53: read: connection reset by peer" question="129.36.168.192.in-addr.arpa. PTR" server="114.114.114.114:53"
time="2019-06-11T10:49:12+08:00" level=error msg="Error hanppens." error="0: read tcp 192.168.1.2:40234->114.114.114.114:53: read: connection reset by peer" question="129.36.168.192.in-addr.arpa. PTR"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61a2c0]

goroutine 134199 [running]:
github.com/miekg/dns.(*Msg).SetEdns0(...)
        C:/Users/Admin/go/pkg/mod/github.com/miekg/dns@v1.1.9/defaults.go:130
github.com/cherrot/gochinadns.setUDPSize(0xc0005ba480, 0x582, 0x69e45a)
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:183 +0xf0
github.com/cherrot/gochinadns.(*Server).Lookup(0xc000364ed0, 0xc0005ba480, 0xc000014344, 0xa, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:81 +0x433
github.com/cherrot/gochinadns.(*Server).Lookup-fm(0xc0005ba480, 0xc000014344, 0xa, 0x645d20, 0xc0004fe330, 0xc000570ae0, 0x20)
        C:/Users/Admin/Desktop/gochinadns-master/dns.go:43 +0x48
github.com/cherrot/gochinadns.lookupInServers.func1(0x0, 0xc000014344, 0xa)
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:34 +0x14b
created by github.com/cherrot/gochinadns.lookupInServers
        C:/Users/Admin/Desktop/gochinadns-master/lookup.go:56 +0x538

```

**Comment by cherrot** [comment]
我先修复竞态条件试试看

**Comment by chk-jxcn** [comment]
> 我先修复竞态条件试试看

测试了一下，可以正常core。。应该是之前启动的时候没有设置好ulimit

**Comment by cherrot** [comment]
有多大？方便的话可以发出来我gdb一把:D

**Comment by chk-jxcn** [comment]
> 有多大？方便的话可以发出来我gdb一把:D

crash的时候没有coredump...应该还要等下次。。大概105M，xz一下400K

**Comment by chk-jxcn** [comment]
上传了log还有coredump，还有coredump对应binary文件

https://pan.baidu.com/s/1GpJJYefJn_HQ3i4mvAf5UA 提取码: nmu3

**Comment by chk-jxcn** [comment]
看起来是在给slice的元素赋值时挂掉的，mov qword ptr [rsi+rbx*1], rdx
但是不知道为啥rsi和rbx都会是0.
```
        defaults.go:124 0x61a271        0f85ea000000            jnz 0x61a361
        defaults.go:124 0x61a277        488d0dcb380800          lea rcx, ptr [runtime.rodata+510793]
        defaults.go:124 0x61a27e        488908                  mov qword ptr [rax], rcx
        defaults.go:125 0x61a281        66c740102900            mov word ptr [rax+0x10], 0x29
        edns.go:128     0x61a287        488b4c2460              mov rcx, qword ptr [rsp+0x60]
        edns.go:128     0x61a28c        66894812                mov word ptr [rax+0x12], cx
        defaults.go:130 0x61a290        488b542458              mov rdx, qword ptr [rsp+0x58]
        defaults.go:130 0x61a295        488b5a78                mov rbx, qword ptr [rdx+0x78]
        defaults.go:130 0x61a299        488b7270                mov rsi, qword ptr [rdx+0x70]
        defaults.go:130 0x61a29d        4c8b8280000000          mov r8, qword ptr [rdx+0x80]
        defaults.go:130 0x61a2a4        4c8d4b01                lea r9, ptr [rbx+0x1]
        defaults.go:130 0x61a2a8        4d39c1                  cmp r9, r8
        defaults.go:130 0x61a2ab        7f40                    jnle 0x61a2ed
        defaults.go:130 0x61a2ad        4c8d4301                lea r8, ptr [rbx+0x1]
        defaults.go:130 0x61a2b1        4c894278                mov qword ptr [rdx+0x78], r8
        defaults.go:130 0x61a2b5        48c1e304                shl rbx, 0x4
        defaults.go:130 0x61a2b9        488d15c03a0c00          lea rdx, ptr [go.itab.*github.com/miekg/dns.OPT,github.c
om/miekg/dns.RR]
        defaults.go:130 0x61a2c0        4889141e                mov qword ptr [rsi+rbx*1], rdx
        defaults.go:130 0x61a2c4        488d7c1e08              lea rdi, ptr [rsi+rbx*1+0x8]
        defaults.go:130 0x61a2c9        833db096270000          cmp dword ptr [runtime.writeBarrier], 0x0
        defaults.go:130 0x61a2d0        7514                    jnz 0x61a2e6
        defaults.go:130 0x61a2d2        4889441e08              mov qword ptr [rsi+rbx*1+0x8], rax
        lookup.go:184   0x61a2d7        48894c2468              mov qword ptr [rsp+0x68], rcx
        lookup.go:184   0x61a2dc        488b6c2448              mov rbp, qword ptr [rsp+0x48]
        lookup.go:184   0x61a2e1        4883c450                add rsp, 0x50
        lookup.go:184   0x61a2e5        c3                      ret
        defaults.go:130 0x61a2e6        e805b6e3ff              call $runtime.gcWriteBarrier
        defaults.go:130 0x61a2eb        ebea                    jmp 0x61a2d7
        defaults.go:123 0x61a2ed        4889442440              mov qword ptr [rsp+0x40], rax
        defaults.go:130 0x61a2f2        488d05473c0500          lea rax, ptr [runtime.rodata+315200]
        defaults.go:130 0x61a2f9        48890424                mov qword ptr [rsp], rax
        defaults.go:130 0x61a2fd        4889742408              mov qword ptr [rsp+0x8], rsi
        defaults.go:130 0x61a302        48895c2410              mov qword ptr [rsp+0x10], rbx
        defaults.go:130 0x61a307        4c89442418              mov qword ptr [rsp+0x18], r8
        defaults.go:130 0x61a30c        4c894c2420              mov qword ptr [rsp+0x20], r9
        defaults.go:130 0x61a311        e89a4be2ff              call $runtime.growslice
        defaults.go:130 0x61a316        488b442428              mov rax, qword ptr [rsp+0x28]
```

**Comment by cherrot** [comment]
似乎当指定了不可达的trusted server后，崩溃很容易发生。 这几天一直没抽出时间来研究，抱歉..

**Comment by cherrot** [comment]
没看出所以然，前几天我也频繁遇到了相同问题，而且core dump里没看出race condition。

改用copy dns message后确实没再出现了，姑且当做糊里糊涂修了吧 :(

**Comment by chk-jxcn** [comment]
> 没看出所以然，前几天我也频繁遇到了相同问题，而且core dump里没看出race condition。
> 
> 改用copy dns message后确实没再出现了，姑且当做糊里糊涂修了吧 :(

在不同的goroutine修改struct应该不是线程安全的。。所以感觉可能还有其他的地方可能会挂？

**Comment by cherrot** [comment]
miekg/dns 在pack msg的时候存在写操作，安全的方式是每个单独请求都使用request的副本，稍后我重构一下
